# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH_M3wXJHpvv81nU1AFGXAawVM9frD1_
"""

import random
population = list(range(1,101))
sample_size = 30
random_sample = random.sample(population, sample_size)
print("Random Sample:" , random_sample)

import numpy as np
import pandas as pd
data = pd.DataFrame({
    'category' : ['A','B','C','D']*25,
    'Value' : np.random.randn(100)
})
Stratified_sample = data.groupby('category',group_keys=False).apply(lambda x: x.sample(2))
print("Stratified Sample:\n", Stratified_sample)

clusters = [list(range(1,50)),list(range(51,75)),list(range(75,92)),list(range(92,100))]
cluster_sample = random.choice(clusters)
print("Cluster Sample:",cluster_sample)

import pandas as pd
import numpy as np
data = pd.DataFrame({
    'values' : np.random.randn(1580)
})
summary = data.describe()
print("Summary Statistics:\n", summary)

import matplotlib.pyplot as plt
data['values'].hist(bins=80,edgecolor='green')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Histogram of Values')
plt.show()

from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(iris.data)
plt.scatter(reduced_data[:,0],reduced_data[:,1],c=iris.target)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Iris Dataset')
plt.show()

#parallel cordinates
from pandas.plotting import parallel_coordinates
data=pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv")
parallel_coordinates(data,'class',color=['b','g','r'])
plt.title('Parallel Coordinates Plot')
plt.xlabel('Attributes')
plt.ylabel('Values')
plt.show()